### ISSUE TITLE
Shared .docx/.odt file is downloaded as a zip archive

### ISSUE THREAD

**Issue by luixxiul** [storj/linksharing#39]
**Description of the issue**: Shared .docx/.odt file is downloaded as a zip archive, which is actually so.

**Steps to reproduce:**

1. Create a `temp.odt` file on Libreoffice
2. `uplink mb sj://share`
3. `uplink cp temp.odt sj://share`
4. `uplink share --url sj://share/temp.odt`
5. Go to the URL of the share file
6. Click "Download"

**Expected result:** the file should be downloaded as an opendocument file

**Actual result:** the file is downloaded as a zip archive

Please feel free to move this issue to a more proper repository if any, thanks.

**Comment by thepaul** [comment]
It looks like we don't set an explicit content-type for served objects, which leaves http.Server to try and detect the type by way of `http.DetectContentType()`. Since .odt and .docx files are both implemented as ZIP files, the only conclusion that DetectContentType can make from the first 512 bytes of the files are that they are ZIP files (`application/zip`).

Most likely we should be setting Content-Type to `application/octet-stream` before serving a file when `?download=on` and maybe when a `/raw/` url is used also. (It's not entirely clear to me what the semantics are supposed to be for all the url and attribute cases.) Browsers handle `application/octet-stream` by simply downloading a file, and generally not trying to display or change anything about it.

**Comment by ifraixedes** [comment]
We plan to work on it in the next sprint.

**Comment by luixxiul** [comment]
@ifraixedes Please do not hesitate to move this issue to a more proper repository if any, where the related code should be fixed (I was not quite sure if `linksharing` was that one).

**Comment by ifraixedes** [comment]
@luixxiul I would say that this is the appropriated repository but I'm not :100: sure.
I think that the most important thing is that's tracked in our internal issue tracker.

By the way, thanks for reporting it!

**Comment by stefanbenten** [comment]
@luixxiul #41 should fix the issue you are having. Once we made a new release tag, i'll update this.

**Comment by luixxiul** [comment]
Thanks for confirmation! I truly appreciate the fix as I wanted to share documents over Tardigrade, deciding by myself with who and until when to share them.

**Comment by VitaliiShpital** [comment]
Hey @luixxiul! We've deployed the fix mentioned above. Could you check if your problem is fixed please?

**Comment by luixxiul** [comment]
Confirmed it was fixed. Now ODF file is properly detected on a browser :+1:
